---
- name: Playbook to create directory and file
  hosts: all
  become: true
  tasks:
  - name: create directory
    file:
      path: /home/ansadmin/dirx
      state: directory

  - name: create file
    file:
      path: /home/ansadmin/dirx/file1
      state: touch
...
